### ISSUE TITLE
Question about the license

### ISSUE THREAD

**Issue by fennectech** [switchbrew/switch-examples#57]
I’m curious what the license permissions are on this.   I would like to use the notification LED example to give sys-ftpd an notification flasher.      That project is GPL-3.0

**Comment by bruhhhhhhhhhh** [comment]
I'm going to assume it's the same license as libnx?

**Comment by fennectech** [comment]
When licens and projects that affect others are involved i like to get concrete answers rather than assumptions.  
You know what they say about assume.   It makes an ass out of u and me

**Comment by tron-pixel** [comment]
Would we be able to kindly get a definitive answer on the license these examples are made available under? This seems like an important question to avoid potential for litigation or DMCA-ing

Github has created the page at https://choosealicense.com to help project maintainers decide on how to make their work available in the way that they want. The page here: https://choosealicense.com/no-permission/ also details the implications of going without a license:

> If you find software that doesn’t have a license, that generally means **you have no permission** from the creators of the software **to use, modify, or share** the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software **for any purpose**.

This issue has been closed without any answers which seems either to be an oversight (most likely) or that the issue is not viewed as important.

The @devkitPro org also seems to be partially (or fully?) involved in ownership of the @switchbrew org. dkP has historically used DMCA to [go after people](https://gbatemp.net/threads/older-versions-of-devkitppc-and-libogc.513964/page-3#post-8434079) for distributing and using their tools in ways that they [don't approve](https://gbatemp.net/threads/collection-of-old-devkitpro-versions.526377/page-5#post-8460666) of (such as making available [historical versions](https://gbatemp.net/threads/collection-of-old-devkitpro-versions.526377/#post-8434947)), or silencing people that [point out licensing issues](https://github.com/devkitPro/buildscripts/issues/20). This makes the desire for license clarification even greater.

More from GH's choosealicense page:

> Ask the maintainers nicely to add a license. Unless the software includes strong indications to the contrary, lack of a license is probably an oversight.

It also suggests suggesting a license– as pointed out here, ISC seems like the intent or a reasonable choice.

If no license is added to this repo, and no clarification is given on how we are permitted to use this code, the no-license page presents another option:
> **Don’t use the software.** Find or create an alternative that is under an open source license.

Thank you to the libnx maintainers, dkP members, and other switchbrew org members for providing + working on these examples, and taking these licensing requests into consideration.

**Comment by TuxSH** [comment]
@tron-pixel 
![image](https://user-images.githubusercontent.com/1922548/61172648-5b279700-a587-11e9-8998-d848a379535e.png)

**Comment by fincs** [comment]
Locking due to this issue being resolved, and also to prevent this from further license trolling, baseless attacks on devkitPro and other misinformation.
